services:
  # US-East
  # US-West
  # EU
  # Asia

  post_db_us_east:
    container_name: post_db_us_east
    build: ./database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=post_db
    volumes:
      - post_db_us_east:/var/lib/postgresql/data

  back:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    container_name: back
    ports:
      - 3000:3000
    volumes:
      - ./back/src:/app/src
    environment:
      PORT: 3000
      POSTGRES_DB: post_db
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_URL: post_db_us_east
    depends_on:
      - post_db_us_east
      # - broker

volumes:
  post_db_us_east:
    driver: local
