services:
  post_db_us_east:
    container_name: post_db_us_east
    build: ./database
    ports:
      - 5101:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=post_db
    volumes:
      - post_db_us_east:/var/lib/postgresql/data

  post_db_us_west:
    container_name: post_db_us_west
    build: ./database
    ports:
      - 5102:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=post_db
    volumes:
      - post_db_us_west:/var/lib/postgresql/data

  post_db_europe:
    container_name: post_db_europe
    build: ./database
    ports:
      - 5103:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=post_db
    volumes:
      - post_db_europe:/var/lib/postgresql/data

  post_db_asia:
    container_name: post_db_asia
    build: ./database
    ports:
      - 5104:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=post_db
    volumes:
      - post_db_asia:/var/lib/postgresql/data

  back:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    container_name: back
    ports:
      - 3000:3000
    volumes:
      - ./back/src:/app/src
    environment:
      PORT: 3000
      POSTGRES_USER_east: admin
      POSTGRES_PASSWORD_east: 123456
      POSTGRES_DB_east: post_db
      POSTGRES_PORT_east: 5101
      POSTGRES_HOST_east: post_db_us_east

      POSTGRES_USER_west: admin
      POSTGRES_PASSWORD_west: 123456
      POSTGRES_DB_west: post_db
      POSTGRES_PORT_west: 5102
      POSTGRES_HOST_west: post_db_us_west

      POSTGRES_USER_europe: admin
      POSTGRES_PASSWORD_europe: 123456
      POSTGRES_DB_europe: post_db
      POSTGRES_PORT_europe: 5103
      POSTGRES_HOST_europe: post_db_europe

      POSTGRES_USER_asia: admin
      POSTGRES_PASSWORD_asia: 123456
      POSTGRES_DB_asia: post_db
      POSTGRES_PORT_asia: 5104
      POSTGRES_HOST_asia: post_db_asia

    depends_on:
      - post_db_us_east
      - post_db_us_west
      - post_db_europe
      - post_db_asia

volumes:
  back_volumen:
    driver: local
  post_db_us_east:
    driver: local
  post_db_us_west:
    driver: local
  post_db_europe:
    driver: local
  post_db_asia:
    driver: local
